### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by sveneggimann** [nismod/ukpopulation#10]
Suggestions: add author and how you would like to have this work quoted.

**Comment by virgesmith** [comment]
would ideally like to follow this: https://guides.github.com/activities/citable-code/
Not sure I can use Zendo to get a DOI on a non-personal repo
In any case I dont have permish to activate the webhook

**Comment by virgesmith** [comment]
Created v1.0.0 with DOI for citation ![release](https://zenodo.org/badge/doi/10.5281/zenodo.1250366.svg)
NOTE: Tom Russell should also be cited as an author
