### ISSUE TITLE
JOSS submission

### ISSUE THREAD

**Issue by virgesmith** [nismod/ukpopulation#13]
- [X] rename to ukpopulation for clearer scope
- [X] write abstract
- [X] fix known bugs #9
- [x] do enhancements #11
- [x] better test coverage
- [x] fix issue with England 2014 SNPP #12
- [x] satisfy any other JOSS requirements

**Comment by soodoku** [comment]
Can you look into satisfying the following JOSS requirement:

"Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

**Comment by soodoku** [comment]
I would also recommend adding how you extrapolate in the ms. but your call.
