### ISSUE TITLE
copyediting

### ISSUE THREAD

**Issue by soodoku** [nismod/ukpopulation#20]
Hey,

1. "The datasets published online in different places and in different formats, depending on the originating agency. "

2. "UK statistics agencies (ONS, StatsWales, NRScotland and NISRA) produce mid-year population estimates, national and subnational population estimates and projections, by single year of age, gender. " ---> I don't know what 'single year of age' means

3. "Population projection variants (e.g. high fertility) are extremely useful for scenario analyses and a number of population projection variants available at national scale. "

4. "This python package aims unify the retrieval of UK-wide data"

etc.

**Comment by virgesmith** [comment]
@soodoku - closing this as have addresses specific points above, pls reopen if anything else
