### ISSUE TITLE
Modify query to handle newly released (2018 based) principal projections from nismod

### ISSUE THREAD

**Issue by ld-archer** [nismod/ukpopulation#39]
Since new principal projections have been released, the package downloads an empty tsv file in place of these projections. Query parameters need to be modified to fix this issue. Also a decision needs to be made about whether we continue using 2016 based projections for now. We could move straight on to the 2018 projections, but this could cause downstream errors, e.g. if paths are ever hard-coded.

**Comment by BenjaminIsaac0111** [comment]
Could just run with the 2018-2118 data just to see if it works?

**Comment by ld-archer** [comment]
Doing that now, I'll try the full static microsimulation if the worked_example works.
Also when we've made whatever changes we're going to make we need to modify the tests. 4/12 tests fail when we run with 2018-2118.

**Comment by BenjaminIsaac0111** [comment]
Received this from NOMIS.

"Dear Benjamin

Thank you for your email, unfortunately when the new projections are released, they replace the existing projections on our website, so unfortunately this is no longer available.

Regards
Freda
Nomis team"
