### ISSUE TITLE
Unable to pull Wales snpp data

### ISSUE THREAD

**Issue by bmcskelly** [nismod/ukpopulation#72]
Upon calling SNPPData.SNPPData() I am receiving an error relating to Wales.

It would seem this call to statswales is being called, which does not work
http://open.statswales.gov.wales/dataset/popu6010?$select=Area_AltCode1,Year_Code,Data,Gender_Code,Age_Code,Area_Hierarchy,Variant_Code&$filter=Gender_Code

Where Gender_Code throws the error.

The exact traceback is ukpopulation/snppdata.py line 25
self.data[utils.WA] = self.__do_wales()
line 286
data += r_data['value']
KeyError: 'value

![image](https://github.com/nismod/ukpopulation/assets/50954979/146ac045-d093-4639-8831-ec45541af31d)

**Comment by virgesmith** [comment]
Sorry @bmcskelly , this package is no longer actively supported. The data providers make a habit of changing protocols, formats etc, so there's probably quite a lot that's broken since the last release - which was 3 years ago.
